name: build-on-pr
on: [ pull_request, workflow_dispatch ]

env:
  LD_LIBRARY_PATH: /usr/local/opt/curl/lib:$LD_LIBRARY_PATH
  PYCURL_SSL_LIBRARY: openssl

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: 'maven'

      - name: Install package dependencies
        run: sudo apt-get install mmv libssl-dev libcurl4-openssl-dev python3-dev python3-pip flake8

      - name: Run maven build
        run: mvn package -B
