name: build-on-merge

on:
  push:
    branches:
      - master
      - sdk_4.4
    tags:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: centos-stream-9
            container-name: el9stream

    env:
      LD_LIBRARY_PATH: /usr/local/opt/curl/lib:$LD_LIBRARY_PATH
      PYCURL_SSL_LIBRARY: openssl
      MAVEN_OPTS: >-
        --add-opens java.base/java.lang=ALL-UNNAMED
        --add-opens java.base/java.lang.reflect=ALL-UNNAMED

    container:
      image: quay.io/ovirt/buildcontainer:${{ matrix.container-name }}
    
    name: Build and test engine-sdk on ${{ matrix.name }}

    steps:
      - uses: ovirt/checkout-action@main

      - name: Update packages
        run: dnf -y update

      - name: Enable EPEL
        run: dnf -y install epel-release

      - name: Install package dependencies
        run: dnf -y install maven python3-pip python3-flake8 openssl-devel libcurl-devel java-21-openjdk-devel

      - name: Set git defaults
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'

      - name: Run maven build
        run: mvn package -B

      - name: Set FOLDER variable according to pushed branch
        run: |
          if [[ ${GITHUB_REF} == 'refs/heads/master' ]];
          then
            echo "REMOTE_BRANCH=main" >> $GITHUB_ENV;
          else
            echo "REMOTE_BRANCH=${GITHUB_REF#refs/heads/}" >> $GITHUB_ENV;
          fi

      - name: Check out target repository
        uses: ovirt/checkout-action@main
        with:
          repository: '${{ secrets.TARGET_REPO }}'
          ssh-key: '${{ secrets.DEPLOY_KEY }}'
          path: python-ovirt-engine-sdk4
          ref: '${{ env.REMOTE_BRANCH }}'

      - name: Copy SDK to repository
        run: |
          rm -rf sdk/target sdk/tests sdk/pom.xml
          cp -r sdk/* ./python-ovirt-engine-sdk4/

      - name: Push changes to python-ovirt-engine-sdk4
        run: |
          cd python-ovirt-engine-sdk4
          if git status --porcelain 2>/dev/null| grep -E "^??|^M"
          then
            git add .
            git commit -am "Sync with upstream"
            git push
          fi
          cd ..
