name: build-on-pr
on:
  [pull_request, workflow_dispatch]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: centos-stream-9
            container-name: el9stream

    env:
      LD_LIBRARY_PATH: /usr/local/opt/curl/lib:$LD_LIBRARY_PATH
      PYCURL_SSL_LIBRARY: openssl
      MAVEN_OPTS: >-
        --add-opens java.base/java.lang=ALL-UNNAMED
        --add-opens java.base/java.lang.reflect=ALL-UNNAMED
      ARTIFACTS_DIR: sdk/lib/ovirtsdk4/

    container:
      image: quay.io/ovirt/buildcontainer:${{ matrix.container-name }}
    
    name: Build and test engine-sdk on ${{ matrix.name }}

    steps:
      - uses: ovirt/checkout-action@main

      - name: Enable EPEL
        run: dnf -y install epel-release

      - name: Install package dependencies
        run: dnf -y install maven python3-pip python3-flake8 openssl-devel libcurl-devel java-21-openjdk-devel

      - name: Run maven build
        run: mvn package -B

      - name: Upload full build folder
        uses: actions/upload-artifact@v4
        with:
          name: generated-ovirtsdk4
          path: ${{ env.ARTIFACTS_DIR }}
